In [46]:
from pybaseball import batting_stats;
import os;
import pandas as pd;
import numpy as np;
import seaborn as sns;
import matplotlib.pyplot as plt;

data = batting_stats(start_season=1871, end_season=2023, league='all', qual=None, ind=0)
df1 = data.loc[data['HR'] > 399]

In [47]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [48]:
total_hr = df1.loc[:,['IDfg','Name','HR']].sort_values('HR', ascending=False)

In [63]:
players = [1000001, 1011327, 1177, 1014040, 1009904, 114, 1004598, 1009405, 97, 1014326, 778, 1010978, 893, 1013975]
total_hr.loc[total_hr['IDfg'].isin(players), ['Name', 'HR']]

                   Name   HR
89           Hank Aaron  755
1             Babe Ruth  714
203       Albert Pujols  703
64          Willie Mays  660
2          Ted Williams  521
27              Mel Ott  511
154      Gary Sheffield  509
3            Lou Gehrig  493
21          Stan Musial  475
120       Chipper Jones  468
318    Carl Yastrzemski  452
160   Vladimir Guerrero  449
1050         Cal Ripken  431
158         Mike Piazza  427
301      Billy Williams  426

In [64]:
total_hr.head(100)

         IDfg               Name   HR
23       1109        Barry Bonds  762
89    1000001         Hank Aaron  755
1     1011327          Babe Ruth  714
203      1177      Albert Pujols  703
130      1274     Alex Rodriguez  696
64    1008315        Willie Mays  660
208       327    Ken Griffey Jr.  630
74        409          Jim Thome  612
392       302         Sammy Sosa  609
85    1011066     Frank Robinson  586
49    1008559       Mark McGwire  583
171   1006905   Harmon Killebrew  573
261      1266    Rafael Palmeiro  569
325   1006308     Reggie Jackson  563
43        210      Manny Ramirez  555
131   1011586       Mike Schmidt  548
152       745        David Ortiz  541
31    1008082      Mickey Mantle  536
6     1004285        Jimmie Foxx  534
46        255       Frank Thomas  521
182   1008423     Willie McCovey  521
2     1014040       Ted Williams  521
165   1008236      Eddie Mathews  512
652   1000512        Ernie Banks  512
27    1009904            Mel Ott  511
235      1744     Miguel Cabrera  511
154       114     Gary Sheffield  509
491   1009386       Eddie Murray  504
228       293       Fred McGriff  493
3     1004598         Lou Gehrig  493
905       639      Adrian Beltre  477
185   1012426    Willie Stargell  475
21    1009405        Stan Musial  475
156      1297     Carlos Delgado  473
120        97      Chipper Jones  468
519   1014127      Dave Winfield  465
532      2434        Nelson Cruz  464
314   1001918       Jose Canseco  462
451       319          Adam Dunn  462
318   1014326   Carl Yastrzemski  452
160       778  Vladimir Guerrero  449
76        547       Jeff Bagwell  449
1150  1006939       Dave Kingman  442
140       818       Jason Giambi  440
581       242       Paul Konerko  439
931   1003091       Andre Dawson  438
689       589     Carlos Beltran  435
230      1251      Juan Gonzalez  434
853        96       Andruw Jones  434
1050  1010978         Cal Ripken  431
158       893        Mike Piazza  427
301   1013975     Billy Williams  426
549      2151  Edwin Encarnacion  424
759   1003864      Darrell Evans  414
981       847    Alfonso Soriano  412
370      1281      Mark Teixeira  409
83    1012230        Duke Snider  407
382      4949  Giancarlo Stanton  402